# Generated by Django 4.1.4 on 2022-12-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='button_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
