# Generated by Django 4.1.4 on 2022-12-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_player_button_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
    ]
