# Generated by Django 4.1.3 on 2022-12-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_deck_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Chips',
            field=models.IntegerField(default=1000),
        ),
    ]
