# Generated by Django 4.1.3 on 2022-12-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_player_chips'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='id_seat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
