# Generated by Django 4.1.3 on 2022-12-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_player_id_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='Card1',
            new_name='card1',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Card2',
            new_name='card2',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Card3',
            new_name='card3',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Card4',
            new_name='card4',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Card5',
            new_name='card5',
        ),
    ]
