# Generated by Django 4.1.3 on 2022-12-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_rename_card1_player_card1_rename_card2_player_card2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
