# Generated by Django 4.1.3 on 2022-12-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_player_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playing',
            field=models.BooleanField(default=False),
        ),
    ]
